e_learning/urls.py
from django.urls import path
from e_learning import views

urlpatterns = [
    path('', views.index, name='index'),
]

urlpatterns += [
    path('lectures/', views.LectureListView.as_view(), name='lecture-list'),
    path('lecture/<int:pk>', views.LectureDetailView.as_view(), name='lecture-detail'),
    path('professors/', views.ProfessorListView.as_view(), name='professor-list'),
    path('professor/<int:pk>', views.ProfessorDetailView.as_view(), name='professor-detail'),
]

urlpatterns += [
    path('streamings/', views.LectureInstanceStreamingListView.as_view(), name='streaming-list'),
    path('enrolledlectures/', views.LectureInstanceMyListView.as_view(), name='my-enroll'),
]

urlpatterns += [
    path('lecture/create/', views.LectureCreate.as_view(), name='lecture_create'),
    path('lecture/<int:pk>/update/', views.LectureUdpate.as_view(), name='lecture_update'),
    path('lecture/<int:pk>/delete/', views.LectureDelete.as_view(), name='lecture_delete'),
]

urlpatterns += [
    path('professor/create', views.ProfessorCreate.as_view(), name='professor_create'),
    path('professor/<int:pk>/update/', views.ProfessorUpdate.as_view(), name='professor_update'),
    path('professor/<int:pk>/delete/', views.ProfessorDelete.as_view(), name='professor_delete'),
]

sanbocompany/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path('e_learning/', include('e_learning.urls')),
]

urlpatterns += [
    path('', RedirectView.as_view(url='/e_learning/', permanent=True)),
]

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

e_learning/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
import uuid
from datetime import date

class Major(models.Model):
    name = models.CharField(
        max_length = 100,
        help_text="Enter a major (e.g. Computer Science, Electronic Science, etc.)"
    )

    def __str__(self):
        return self.name

class Language(models.Model):
    name = models.CharField(max_length=200, help_text="Enter the lecture's language (e.g. English, Korean, Japanese etc.)")

    def __str__(self):
        return self.name

class Lecture(models.Model):
    title = models.CharField(max_length=200)
    professor = models.ForeignKey('Professor', on_delete=models.SET_NULL, null=True)
    summary = models.TextField(max_length=1000, help_text="Enter a brief descriptiuon of the book")
    major = models.ForeignKey('Major', on_delete=models.SET_NULL, null=True)
    language = models.ForeignKey('Language', on_delete=models.SET_NULL, null=True)

    def get_absolute_url(self):
        return reverse('lecture-detail', args=[str(self.id)])

    def __str__(self):
        return self.title

class Assignment(models.Model):
    name = models.CharField(max_length=200)
    due_date = models.DateField(null=True, blank=True)

    def __str__(self):
        return self.name


class LectureInstance(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                             help_text="Unique ID for this particular lecture across whole website")
    lecture = models.ForeignKey('Lecture', on_delete=models.SET_NULL, null=True)
    assignment = models.ForeignKey('Assignment', on_delete=models.SET_NULL, null=True)
    remain_time = models.DateField(null=True, blank=True)
    enroll_student = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    @property
    def is_overdue(self):
        if self.remain_time and date.today() > self.remain_time:
            return True
        return False

    LECTURE_STATUS = (
        ('o', 'Opened'),
        ('c', 'Closed'),
        ('s', 'Streaming'),
        ('e', 'Exam'),
    )

    status = models.CharField(
        max_length=1,
        choices=LECTURE_STATUS,
        blank=True,
        default='o',
        help_text='Lecture is Opened now. You can take VOD Service.'
    )

    class Meta:
        ordering = ['remain_time']
        permissions = (("can_modified_remain_time", "Set remain time"),)

    def __str__(self):
        return '{0} ({1})'.format(self.id, self.lecture.title)

class Professor(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    major = models.ForeignKey('Major', on_delete=models.SET_NULL, null=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        return reverse('professor-detail', args=[str(self.id)])

    def __str__(self):
        return '{0}, {1}'.format(self.last_name, self.first_name)

e_learning/forms.py
import datetime

from django import forms
from .models import LectureInstance
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

class RenewLectureForm(forms.Form):
    renewal_date = forms.DateField(help_text="Enter a date between now and 2 weeks (default 3).")

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        # Check if a date is not in the past.
        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))

        # Check if a date is in the allowed range (+2 weeks from today).
        if data > datetime.date.today() + datetime.timedelta(weeks=2):
            raise ValidationError(_('Invalid date - renewal more than 2 weeks ahead'))

        # Remember to always return the cleaned data.
        return data

e_learning/views.py
import datetime

from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy

# Authentication
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import  LoginRequiredMixin, PermissionRequiredMixin

from e_learning.models import Lecture, Professor, LectureInstance, Language, Major, Assignment

@login_required
def index(request):
    num_lectures = Lecture.objects.all().count()
    num_lecture_instances = LectureInstance.objects.all().count()
    num_streamings = LectureInstance.objects.filter(status__exact='s').count()
    num_professors = Professor.objects.count()

    # session별 방문횟수
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    context = {
        'num_lectures' : num_lectures,
        'num_lecture_intance' : num_lecture_instances,
        'num_streamings' : num_streamings,
        'num_professors' : num_professors,
        'num_visits' : num_visits,
    }

    return render(request, 'index.html', context=context)

"""
Lecture View
"""
class LectureListView(LoginRequiredMixin, generic.ListView):
    model = Lecture
    paginate_by = 5

class LectureDetailView(LoginRequiredMixin, generic.DetailView):
    model = Lecture

"""
Professor View
"""
class ProfessorListView(LoginRequiredMixin, generic.ListView):
    model = Professor
    paginate_by = 5

class ProfessorDetailView(LoginRequiredMixin, generic.DetailView):
    model = Professor

"""
Lecture instance View
"""
class LectureInstanceListView(LoginRequiredMixin, generic.ListView):
    model = LectureInstance
    template_name = 'e_learning/lectureinst_list.html'
    paginate_by = 10

    def get_queryset(self):
        return LectureInstance.objects.filter(status__exact='o').order_by('remain_time')

class LectureInstanceStreamingListView(LoginRequiredMixin, generic.ListView):
    model = LectureInstance
    template_name = 'e_learning/lectureinst_streaming_list.html'
    paginate_by = 10

    def get_queryset(self):
        return LectureInstance.objects.filter(status__exact='s').order_by('remain_time')

class LectureInstanceMyListView(LoginRequiredMixin, generic.ListView):
    model = LectureInstance
    template_name = 'e_learning/lectureinst_my_list.html'
    paginate_by = 10

    def get_queryset(self):
        return LectureInstance.objects.filter(enroll_student=self.request.user).filter(status__exact='o').order_by('remain_time')

"""
form
"""
from .forms import RenewLectureForm

@permission_required('e_learning.can_modified_remain_time')
def renew_lecture_staff(request, pk):
    lecture_instance = get_object_or_404(LectureInstance, pk=pk)

    if request.method == 'POST':
        form = RenewLectureForm(request.POST)

        if form.is_vaild():
            lecture_instance.due_date = form.cleaned_data['renewal_date']
            lecture_instance.save()

            ## return HttpResponseRedirect(reverse('all-borrowed')) 수정필요
    else: # GET request
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=2)
        form = RenewLectureForm(initial={'renewal_date': proposed_renewal_date})

        context = {
            'form' : form,
            'lecture_instance' : lecture_instance,
        }

        return render(request, 'catalog/lecture_renew_staff.html', context)

"""
Lecture Create / Update /Delete
"""
from .models import Lecture

class LectureCreate(PermissionRequiredMixin, CreateView):
    model = Lecture
    fields = '__all__'
    permission_required = 'e_learning.can_modified_remain_time'

class LectureUdpate(PermissionRequiredMixin, UpdateView):
    model = Lecture
    fields = '__all__'
    permission_required = 'e_learning.can_modified_remain_time'

class LectureDelete(PermissionRequiredMixin, DeleteView):
    model = Lecture
    success_url = reverse_lazy('lectures')
    permission_required = 'e_learning.can_modified_remain_time'

"""
Professor Create / Update / Delete
"""
from .models import Professor

class ProfessorCreate(PermissionRequiredMixin, CreateView):
    model = Professor
    fields = '__all__'
    initial = {'date_of_birth' : '01/01/2020',}
    permission_required = 'e_learning.can_modified_remain_time'

class ProfessorUpdate(PermissionRequiredMixin, UpdateView):
    model = Professor
    fields = ['fist_name', 'last_name', 'date_of_birth', 'major'] ## '__all__'은 안되나?
    permission_required = 'e_learning.can_modified_remain_time'

class ProfessorDelete(PermissionRequiredMixin, DeleteView):
    model = Professor
    success_url = reverse_lazy('professors')
    permission_required = 'e_learning.can_modified_remain_time'

e_learning/templates/e_learning/assignment_renew_professor.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Renew: {{ open_lecture.lecture.title }}</h1>
    <p{% if open_lecture.is_overdue %} class="text-danger"{% endif %}>Due date: {{ open_lecture.remain_time }}</p>

    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit"/>
    </form>
{% endblock %}

e_learning/templates/e_learning/lecture_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

    <h1>Delete lecture</h1>

    <p>Are you sure you want to delete the lecture: {{ lecture }}</p>

    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" action="" value="Yes, delete." />
    </form>
{% endblock %}

e_learning/templates/e_learning/lecture_detail.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Title : {{ lecture.title }}</h1>

    <p><strong>Professor:</strong><a href="{% url 'professor-detail' lecture.professor.pk %}">{{ lecture.professor }}</a></p>
    <p><strong>Summary:</strong> {{ lecture.summary }}</p>
    <p><strong>Major:</strong>{{ lecture.major }}</p>
    <p><strong>Language:</strong>{{ lecture.language }}</p>

    <div style="margin-left:20px; margin-top:20px">
        <h4>VOD</h4>
        <!-- video.js code -->
            <video id="my-player" class="video-js" controls preload="auto" poster="s3://vod-mediabucket-sihyung/test/Default/Thumbnails/test.0000000.jpg" data-setup='{}'>
                <source src="https://d387almvgdyqi8.cloudfront.net/Sanbo/Default/HLS/Sanbo.m3u8" type="application/x-mpegURL"></source>
            </video>
{#        {% for opened in lecture.lecture_instance_set.all %}#}
{#        <hr>#}
{#        <p class="{% if opened.status == 'o' %}text-success{% elif opened.status == 'c' %}text-warning{% endif %}">{{ opened.get_status_display }}</p>#}
{#        {% if opened.status != 'e' %}#}
{#            <p><strong>This lecture is examing now!</strong></p>#}
{#        {% endif %}#}
{#            <p><strong>Remain-time:</strong>{{ opened.remain_time }}</p>#}
{#            <p class="text-muted"><strong>ID:</strong>{{ opened.id }}</p>#}
{#        {% endfor %}#}
    </div>
{% endblock %}

e_learning/templates/e_learning/lecture_form.html
{% extends "base_generic.html" %}

{% block content %}

    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit">
    </form>
{% endblock %}

e_learning/templates/e_learning/lecture_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Lecture List</h1>
    {% if perms.e_learning.can_modified_remain_time %}<a href="{% url 'lecture_create' %}"> [Create]</a>{% endif %}
    {% if lecture_list %}
    <ul>
        {% for lecture in lecture_list %}
            <li>
                <a href="{{ lecture.get_absolute_url }}">{{ lecture.title }}</a>
                {% if perms.e_learning.can_modified_remain_time %} / <a href="{% url 'lecture_update' lecture.id %}" style="color:green" /> [Update] </a> {% endif %}
                {% if perms.e_learning.can_modified_remain_time %} / <a href="{% url 'lecture_delete' lecture.id %}" style="color:red" /> [Delete] </a> {% endif %}
            </li>
        {% endfor %}
    </ul>
    {% else %}
        <p>There are no lectures...</p>
    {% endif %}
{% endblock %}

e_learning/templates/e_learning/lectureinst_my_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>My lecture</h1>

    {% if lectureinstance_list %}
        <ul>
            {% for lectureinstance in lectureinstance_list %}
                <li class="{% if lectureinstance.is_overdue %}text-danger{% endif %}">
                    <a href="{% url 'lecture-detail' lectureinstance.lecture.pk %}">{{ lectureinstance.lecture.title }}</a>
                </li>
            {% endfor %}
        </ul>

    {% else %}
        <p>There are no Enrolled lectures.</p>
    {% endif %}
{% endblock %}

e_learning/templates/e_learning/lectureinst_streaming_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Streaming Now</h1>
     <!-- video.js code -->
            <video id="streaming"
                   class="video-js"
                   controls preload="auto"
                   data-setup='{}'
                   width="960"
                   height="540"
                   controls>
                <source src="https://d2e5bgkk9yt2xe.cloudfront.net/livea/main_1080p30.m3u8" type="application/x-mpegURL"></source>
            </video>
{#    {% if lectureinstance_list %}#}
{#    <ul>#}
{#        {% for lectureinstance in lectureinstance_list %}#}
{#            <li>#}
{#                <a href="{% url 'lecture-detail' lectureinstance.lecture.pk %}">{{ lectureinstance.lecture.title }}</a>#}
{#                {% if lectureinstance.get_queryset %}#}
{#                    <a href="{% url 'lecture-detail' lectureinstance.lecture.pk %}">{{ lectureinstance.lecture.title }}</a>#}
{#                {% endif %}#}
{#            </li>#}
{#        {% endfor %}#}
{#    </ul>#}
{#    {% else %}#}
{#        <p>There are no lectures...</p>#}
{#    {% endif %}#}
{% endblock %}

e_learning/templates/e_learning/openlecture_list_all.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Opened lecture</h1>

    {% if openlecture_list %}
        <ul>
            {% for openlec in openlecture_list %}
            <li class="{% if openlec.is_overdue %}"text-danger{% endif %}">
            <a href="{% url 'lecture-detail' openlec.lecture.pk %}">{{ openlec.lecture.title }}</a> ({{ openlec.remain_time }})
                <!-- permission renew -->
            </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>There are no openlectures.</p>
    {% endif %}
{% endblock %}

e_learning/templates/e_learning/openlecture_list_enroll_student.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>My lecture</h1>

    {% if openlecture_list %}
        <ul>
            {% for openlec in openlecture_list %}
            <li class="{% if openlec.is_overdue %}text-danger{% endif %}">
                <a href="{% url 'lecture-detail' openlec.lecture.pk %}">{{ openlec.lecture.title }}</a>
            </li>
            {% endfor %}
        </ul>

    {% else %}
        <p>There are no Enrolled lectures.</p>
    {% endif %}
{% endblock %}

e_learning/templates/e_learning/professor_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

    <h1>Delete Professor</h1>

    <p>Are you sure you want to delete the Professor: {{ professor }}</p>

    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" action="" value="Yes, delete." />
    </form>
{% endblock %}

e_learning/templates/e_learning/professor_detail.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Professor : {{ professor }}</h1>
    <p>{{ professor.date_of_birth }} / {{ professor.major }}</p>

    <div style="margin-left:20px; margin-top:20px">
    <h4>Lectures</h4>

    <dl>
        {% for lecture in professor.lecture_set.all %}
            <dt><a href="{% url 'lecture-detail' lecture.pk %}">{{ lecture }}</a></dt>
            <dd>{{ lecture.summary }}</dd>
        {% endfor %}
    </dl>
    </div>
{% endblock %}

e_learning/templates/e_learning/professor_form.html
{% extends "base_generic.html" %}

{% block content %}

    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit">
    </form>
{% endblock %}

e_learning/templates/e_learning/professor_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Professor List</h1>
    {% if perms.e_learning.can_modified_remain_time %}<a href="{% url 'professor_create' %}"> [Create]</a>{% endif %}
    {% if professor_list %}
    <ul>
        {% for professor in professor_list %}
            <li>
                <a href="{{ professor.get_absolute_url }}">{{ professor.last_name }} {{ professor.first_name }} ({{professor.date_of_birth }} - )</a>
                {% if perms.e_learning.can_modified_remain_time %} / <a href="{% url 'professor_update' professor.id %}" style="color:green" /> [Update] </a> {% endif %}
                {% if perms.e_learning.can_modified_remain_time %} / <a href="{% url 'professor_delete' professor.id %}" style="color:red" /> [Delete] </a> {% endif %}
            </li>
        {% endfor %}
    </ul>
    {% else %}
        <p>There are no professors...</p>
    {% endif %}
{% endblock %}